### PR TITLE
Fix csq failure

### PR DESCRIPTION
**Pull request by zlskidmore**

### CODE REVIEW

**Comment by zlskidmore** [comment]
This is only a partial fix, and could probably be cleaned up a bit, if the length of alts for a missing csq entry was ever > 1 this would fail

**Comment by zlskidmore** [comment]
made change suggested by @tmooney

**Review by tmooney — APPROVED** [review]
+1, makes sense to me with the `for alt in alts:` loop!

**Review by susannasiebert — APPROVED** [review]
+1

**Pull request merged**
